### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by LTLA** [ArtifactDB/gobbler#5]
- [x] Authorize maintainers always.
- [x] Handle latest refresh requests from maintainers.
- [x] Handle usage refresh requests from maintainers.
- [x] Handle probation approval/disapproval requests.
- [x] Create event logs.
- [x] Add an `isMissingOrBadName` for quick checks.
- [x] Test correct generation of the `..links` file.
- [x] Differentiate between request parameters and metadata.
