### ISSUE TITLE
TODO list mark 2

### ISSUE THREAD

**Issue by LTLA** [ArtifactDB/gobbler#8]
- [x] Avoid deleting the `responses` directory during purges.
- [x] Purge the contents of the `..log` directory every now and then.
- [x] Delete version directories in the registry if the upload failed.
- [x] Add deletion endpoints for administrators.
